[app]
name = "TalentRank"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"
git_port = "50051"
llm_port = "50052"


[mysql]
host = "111.229.114.251"
port = "3306"
username = "mydb"
password = "12345678"
database = "mydb"